### ISSUE TITLE
hid publish not processing to html?

### ISSUE THREAD

**Issue by gizmomathboy** [genehack/HiD#43]
1. installed HiD-1.98
2. in newly created dir (~/temp/hid) ran 'hid init'
3. edited _config.yaml to have url: 'http://localhost:5000'
4. created index.mkdn
5. ## edited index.mkdn to contain:
   
   layout: default
   ## title: Hello, World!
   # Hello World, should be h1
6. Then created dir _posts
7. in _posts created file 1999-09-09-first-post.html (from HiD::App::Command::init example/sub ( https://metacpan.org/source/GENEHACK/HiD-1.98/lib/HiD/App/Command/init.pm )
8. edited file from step 7 to have content per example sub noted in step 7.
9. cd ~/temp/hid
10. ran 'hid publish'
11. ran 'hid server'
12. went to browser and checked http://localhost:5000 to see how index.html rendered. Got [% content %]. This is the from _layouts/default.html
13. checked http://localhost:5000/1999/09/09/first-post.html and also go t [% content %] which I think is more wrong since the sub/example in step 7. creates a layout for post.html that has more stuff that should be displayed.
14. as noted on irc chat I have a repo of this hellow world example at https://github.com/gizmomathboy/hid_hello_world

Hopefully enough detail (that is mostly the steps I followed) to recreate what I am seeing.

**Comment by rjgoldsborough** [comment]
I found a few things here. I fixed them in a branch at https://github.com/rjgoldsborough/hid_hello_world/tree/hid-not-publishing

The main error I found for HiD not publishing was no "processor type".  The available options can be found here https://github.com/genehack/HiD/tree/master/lib/HiD/Processor. I added Template to the config.

I also changed the main index page to HTML. I actually don't know if this is required, but it's how I/we (II) use it.

I didn't see a "First Post" but your url is going to be http://localhost:5000/2016/07/28/hello-world.html because the file is named 2016-07-28-hello-world.md. (I also switched to md. Again, just because that's what I/we (II) use.)

If you have any other questions, lemme know.
